apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: bigdata-pipeline
data:
  bucket_config.yaml: |
    type: S3
    config:
      bucket: thanos
      endpoint: minio:9000
      access_key: minioadmin
      secret_key: minioadmin123
      insecure: true

  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'mongodb_exporter'
        static_configs:
          - targets: ['mongodb-exporter:9216']
      - job_name: 'weather_exporter'
        static_configs:
          - targets: ['weather-exporter:8000']
      - job_name: 'node_exporter'
        static_configs:
          - targets: ['node-exporter:9100']