apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: bigdata-pipeline
data:
  # Tên host "mongo" ở đây phải trùng với tên Service của mongo ở phần 2
  MONGO_URI: "mongodb://mongo:mongo123@mongodb:27017/weather_db?authSource=admin"
  PORT: "3000"
  WEATHER_COLLECTION_NAME: "stream_data"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: bigdata-pipeline
type: Opaque
stringData:
  # Token mapbox của bạn (K8s sẽ tự mã hóa base64 khi lưu)
  MAPBOX_TOKEN: "pk.eyJ1IjoibnR0aGFuaDA4MDMiLCJhIjoiY21oeDJmZzZ5MDY2NjJsb3VmMmw2cnZvbiJ9.SidifhDOD6tL4x_qYkjEBw"