apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Tên host "mongo" ở đây phải trùng với tên Service của mongo ở phần 2
  MONGO_URI: "mongodb://mongo:27017/weather_db"
  PORT: "3000"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Token mapbox của bạn (K8s sẽ tự mã hóa base64 khi lưu)
  MAPBOX_TOKEN: "pk.eyJ1IjoibnR0aGFuaDA4MDMiLCJhIjoiY21oeDJmZzZ5MDY2NjJsb3VmMmw2cnZvbiJ9.SidifhDOD6tL4x_qYkjEBw"