apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: default
spec:
  ports:
  - port: 2181
    targetPort: 2181
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: default
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper
        ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: default
spec:
  # NodePort allows you to access it from localhost (for your Python Producer script)
  type: NodePort
  ports:
  - port: 9092
    targetPort: 9092
    nodePort: 30092
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:2.13-2.8.1
        ports:
        - containerPort: 9092
        env:
        # Connect to Zookeeper
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181
        # Advertise the internal DNS name so Spark can find it
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-service.default.svc.cluster.local:9092
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
        # Allow automatic topic creation
        - name: KAFKA_CREATE_TOPICS
          value: "weather_data:1:1"