apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: connect-configs
  namespace: bigdata-pipeline
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
    cleanup.policy: compact
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: connect-status
  namespace: bigdata-pipeline
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
    cleanup.policy: compact
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: connect-offsets
  namespace: bigdata-pipeline
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
    cleanup.policy: compact